version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: ${PROJECT}_db
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: always
    networks:
      - local
  common:
    image: ${PROJECT}_base
    container_name: ${PROJECT}_common
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'yarn watch:common'
    volumes:
      - ./node_modules:/node_modules
      - ./packages:/packages
  api:
    image: ${PROJECT}_base
    container_name: ${PROJECT}_api
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'yarn watch:api'
    volumes:
      - ./node_modules:/node_modules
      - ./apps/api:/apps/api
      - ./packages:/packages
    ports:
      - '4000:4000'
    env_file:
      - ./.env
    environment:
      - BUILD_ID=${COMMIT_SHA}
      - BUILD_INFO=${LAST_COMMIT_MESSAGE}
    depends_on:
      - db
      - common
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:latest # later than 22.0.1
    container_name: ${PROJECT}-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    command: 'start-dev --import-realm'
    volumes:
      - ./keycloak/realm-ehpr.json:/opt/keycloak/data/import/realm-ehpr.json
    ports:
      - '8080:8080'
    networks:
      - local

  web:
    image: ${PROJECT}_base
    container_name: ${PROJECT}_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'yarn watch:web'
    volumes:
      - ./node_modules:/node_modules
      - ./apps/web:/apps/web
      - ./packages:/packages
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
      - RUNTIME_ENV=local
      - NEXT_PUBLIC_KC_URL=${NEXT_PUBLIC_KC_URL}
      - NEXT_PUBLIC_KC_REALM=${NEXT_PUBLIC_KC_REALM}
      - NEXT_PUBLIC_KC_CLIENT_ID=${NEXT_PUBLIC_KC_CLIENT_ID}
      - NEXT_PUBLIC_KC_REDIRECT_URI=${NEXT_PUBLIC_KC_REDIRECT_URI}
      - NEXT_PUBLIC_FEATURE_MASS_EMAIL=${NEXT_PUBLIC_FEATURE_MASS_EMAIL}
      - NEXT_PUBLIC_PREFILLED_FORM=${NEXT_PUBLIC_PREFILLED_FORM}
    depends_on:
      - api
networks:
  local:
    driver: bridge
