version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: ${PROJECT}_db
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ehpr-admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ehpr2
    restart: always
    networks:
      - local
  api:
    image: ${PROJECT}_base
    container_name: ${PROJECT}_api
    build: 
      context: ./
      dockerfile: Dockerfile
    command: 'yarn watch:api'
    ports:
      - '4000:4000'
    environment: 
      - NODE_ENV=development
      - RUNTIME_ENV='hosted
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
  
  web:
    image: ${PROJECT}_base
    container_name: ${PROJECT}_web
    build: 
      context: ./
      dockerfile: Dockerfile
    command: 'yarn watch:web'
    ports:
      - '3000:3000'
    environment: 
      - NODE_ENV=development
      - RUNTIME_ENV='hosted
    depends_on:
      - api
networks:
  local:
    driver: bridge
