name: Web PR Checks
on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @ehpr/web install

      - name: Run formatting check
        run: yarn format:check

      - name: Build dependencies
        run: yarn build-common

      - name: Lint web package
        run: yarn workspace @ehpr/web lint

      - name: Test web package
        run: yarn workspace @ehpr/web test

      - name: Start web app
        run: PREFILLED_FORM=true yarn workspace @ehpr/web dev &

      - name: sleep until webapp is up
        run: |
          until $(curl --silent --fail http://localhost:3000); do
              echo '.'
              ((c++)) && ((c==10)) && c=0 && break # don't run more than 10 times
              sleep 5
          done

      - name: Accessibility Test web package
        run: make accessibility-test

      - name: Build web package
        run: yarn workspace @ehpr/web build
