name: API PR Checks
on:
  pull_request:
    paths:
      - 'apps/api/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @ehpr/api install

      - name: Run formatting check
        run: yarn format:check

      - name: Build dependencies
        run: yarn build-common

      - name: Lint API Package
        run: yarn workspace @ehpr/api lint

      - name: Test API Package
        run: yarn workspace @ehpr/api test

      - name: Build API Package
        run: yarn workspace @ehpr/api build

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: ${{ secrets.DEV_URL }}
          cmd_options: '-I'
