name: Web PR Checks
on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/common/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Install dependencies
        run: yarn workspace @ehpr/web install

      - name: Run formatting check
        run: yarn format:check

      - name: Build dependencies
        run: yarn build-common

      - name: Lint web package
        run: yarn workspace @ehpr/web lint

      - name: Test web package
        run: yarn workspace @ehpr/web test

      - name: Build web package
        run: yarn workspace @ehpr/web build
