name: Terraform PR check

on:
  pull_request:
    paths:
      - 'terraform/**'

env:
  PROJECT: ehpr
  NODE_ENV: development
  ENV_NAME: dev

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      CLOUDFRONT_ID: '${{ secrets.CLOUDFRONT_ID }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Print local env
        run: make print-env

      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Setup terraform dir
        run: make pre-build

      - name: Build web app
        run: make build-web

      - name: Build api
        run: make build-api

      - name: Run Terraform Plan
        run: make plan
