name: ZAP Scan
on:
  pull_request:

env:
  PROJECT: ehpr
  ENV_NAME: prod
  TF_VERSION: 1.1.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${github.ref}-sec
    environment:
      name: prod
    env:
      CLOUDFRONT_ID: '${{ secrets.CLOUDFRONT_ID }}'

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://https://ehpr.gov.bc.ca/'
          cmd_options: '-I'
          rules_file_name: '.zap/rules.tsv'
